### ISSUE TITLE
Generated form component gives TS error for nullable fields

### ISSUE THREAD

**Issue by LilyRose2798** [nicoalbanese/kirimase#71]
The steps I ran to get this error were the following:

1. `bun create next-app` with all defaults except for enabling `src` folder
2. `kirimase init` with following settings:
    - `src` folder: Yes
    - package manager: Bun
    - component library: Shadcn UI
    - ORM: Drizzle
    - DB type: Postgres
    - DB provider: Postgres.JS
    - example model: no
    - authentication package: Clerk
    - misc packages: TRPC
3. `kirimase generate` with following settings:
    - resources to generate: Model, TRPC, Views + Components
    - table name: posts
    - field type: text
    - field name: description
    - required?: no
    - another field?: no
    - index?: no
    - belongs to user?: yes

The result has a single error in the generated component at `src/components/posts/PostForm.tsx` with the `Input` component within the `description`'s `FormControl`. The error is the following:
```
Types of property 'value' are incompatible.
    Type 'string | null' is not assignable to type 'string | number | readonly string[] | undefined'.
      Type 'null' is not assignable to type 'string | number | readonly string[] | undefined'.
```
![image](https://github.com/nicoalbanese/kirimase/assets/1974590/0d72eb70-f599-4660-acc7-7a4e4f4f4c4e)

I'm not sure what the best way to deal with this is, but I've temporarily added `value=""` to the end of the `Input` props which silences the error. Any ideas on a better way to handle this? I would have thought that handling nullable fields was the purpose of the `defaultValues` defined earlier in that file, but maybe the `zodResolver` bug mentioned is the root cause of the issue?

Any help would be appreciated.

**Comment by nykko7** [comment]
I went through the same problem. My workaround was to do this:

`<Input {...field} value={field.value ?? ""} />`

**Comment by nicoalbanese** [comment]
Hey @LilyRose2798 - thanks for flagging this! This issue started happening with a newer release of Zod and I haven't found a great solution as of yet beyond just @ts-ignore ing the error. It's happening because of the optional value that get's handed into the resolver. In the resolver code we do something like `defaultValues = resource ?? { value1: ... value2: ...}` and so even though we provide a default value, in the case where resource is not null, the value1 is still potentially null/undefined. I think you could, rather than writing out `defaultValue = resource ?? ...` you could do write out each value ie `defaultValues  = { value1: resource.value1 ?? "" ... }` but that sounds quite tedious. I'm keeping my eye out for a solution and please let me know if you come to any sort of fix. @nykko7 I didn't have any luck with that as my input was then bound to "" with no ability to update but will try and again and let you both know if it solves it for me.
