### ISSUE TITLE
init fails on new app

### ISSUE THREAD

**Issue by 4ware** [nicoalbanese/kirimase#82]
❯ pnpx create-next-app@latest
Packages: +1
+
Progress: resolved 1, reused 0, downloaded 1, added 1, done
✔ What is your project named? … test
✔ Would you like to use TypeScript? …  Yes
✔ Would you like to use ESLint? … Yes
✔ Would you like to use Tailwind CSS? … Yes
✔ Would you like to use `src/` directory? … Yes
✔ Would you like to use App Router? (recommended) … Yes
✔ Would you like to customize the default import alias (@/*)? … No

❯ cd test
❯ kirimase init

 FATAL  Kirimase only works with the Next.js App Directory.

**Comment by CsarChvz** [comment]
I think its not working beacuse the approuter problem with trpc :)

**Comment by nicoalbanese** [comment]
Hey @4ware - thanks for flagging and sorry about the issue. This has been resolved with ac00576 and is now fixed with 0.0.31. If you run kirimase@latest, you should be good to go!

**Comment by 4ware** [comment]
Thanks a lot! It works now!! But is there any docs how to implemeent a privateProcedure with clerk??

**Comment by nicoalbanese** [comment]
Awesome! So for adding a protected route, in theory, it's as easy as adding a call to getUserAuth() in context.ts and then returning the destructured session. I wrote up some more info on this the other day on discord which ill include below. However, there is a known issue right now with clerk where for some reason, their headers are not being stored properly and it's leading to null auth objects when trying to access server side (active thread from theo's discord here: https://discord.com/channels/966627436387266600/1170848397570359376). I'm waiting to hear from Clerk team what they suggest and will add a solution once they comment on it.

---
"Spent a few hours yesterday trying to get an answer over, but ran into a big issue with Clerk while doing it that led to some refactoring on the trpc code that Kirimase generates for server side invokation. We're still running to an issue with Clerk (for some reason the clerk headers are saying the user is signed out which is leading the auth object to equal null). However, once that is sorted, it's really easy. You just add a call to getUserAuth() in the context file and add it to the return object.
```
import { FetchCreateContextFnOptions } from "@trpc/server/adapters/fetch";
import { getUserAuth } from "@/lib/auth/utils";

export async function createContext(opts?: FetchCreateContextFnOptions) {
  const { session } = await getUserAuth();

  return {
    session: session,
    headers: opts && Object.fromEntries(opts.req.headers),
  };
}

export type Context = Awaited<ReturnType<typeof createContext>>;
```

Then add the following to the end of your `server/trpc.ts`
```
const isAuthed = t.middleware(({ next, ctx }) => {
  if (ctx.session === null) {
    throw new TRPCError({ code: "UNAUTHORIZED" });
  }

  return next({
    ctx: {
      session: ctx.session,
    },
  });
});
export const protectedProcedure = t.procedure.use(isAuthed);
```
and then you should be good to go 😄

keep in mind, I was running into issues with the previous implementation of server-side invokation that was using NextCacheLink and have since moved it to unstable_httpBatchStreamLink. So if you have a project that was scaffolded a few days ago,  you may run into the issue where (when invoking server-side), your server return s a trpc error, but the function still returns a cache'd payload (which is really annoying and not desirable)."

**Comment by 4ware** [comment]
Thankks a lot! That really helped!!
